import React from "react"
import { ClayCard } from "../components/clay"
import { Shield01Icon, File01Icon, CheckmarkSquare03Icon, SparkleIcon } from "../lib/icons"

export default function Terms() {
  return (
    <div className="flex flex-col gap-8 max-w-5xl mx-auto py-4">
      {/* Hero */}
      <div className="pt-2 pb-3 border-b border-[var(--border)]/60">
        <h1
          className="text-2xl sm:text-[30px] font-bold text-text-primary tracking-tight"
          style={{ fontFamily: "var(--font-display)" }}
        >
          Terms of Service
        </h1>
        <p className="mt-1.5 text-sm sm:text-[15px] text-text-secondary leading-relaxed max-w-2xl">
          Clear, transparent operating terms designed to protect content creators, creative assets, and intellectual property.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <ClayCard>
          <div className="flex flex-col gap-3 p-2">
            <div className="w-10 h-10 rounded-2xl bg-indigo-50 text-primary flex items-center justify-center font-bold">
              <SparkleIcon size={20} />
            </div>
            <h3 className="font-bold text-base text-text-primary font-[var(--font-display)]">
              100% Creator IP Ownership
            </h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              All scripts, retention hooks, scene teleprompter beats, Imagen 3 thumbnail concept layouts, and Lyria AI music tracks generated by your autonomous fleet belong <strong>100% exclusively to you</strong>. Crewmate claims zero royalty or derivative rights.
            </p>
          </div>
        </ClayCard>

        <ClayCard>
          <div className="flex flex-col gap-3 p-2">
            <div className="w-10 h-10 rounded-2xl bg-emerald-50 text-emerald-600 flex items-center justify-center font-bold">
              <File01Icon size={20} />
            </div>
            <h3 className="font-bold text-base text-text-primary font-[var(--font-display)]">
              Autonomous Advisory Role
            </h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              Crewmate agents operate as autonomous intelligence co-pilots. Contract redlines, risk assessments, and compliance audits provide decision support; the creator retains sole and final authority over executed sponsor agreements and published media.
            </p>
          </div>
        </ClayCard>

        <ClayCard>
          <div className="flex flex-col gap-3 p-2">
            <div className="w-10 h-10 rounded-2xl bg-purple-50 text-purple-600 flex items-center justify-center font-bold">
              <Shield01Icon size={20} />
            </div>
            <h3 className="font-bold text-base text-text-primary font-[var(--font-display)]">
              FTC & Platform Compliance
            </h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              The Compliance Shield scans titles and descriptions against FTC 16 CFR § 255 and platform community guidelines. Exported Compliance Certificates provide proof of diligence for commercial brand partners and regulatory bodies.
            </p>
          </div>
        </ClayCard>

        <ClayCard>
          <div className="flex flex-col gap-3 p-2">
            <div className="w-10 h-10 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center font-bold">
              <CheckmarkSquare03Icon size={20} />
            </div>
            <h3 className="font-bold text-base text-text-primary font-[var(--font-display)]">
              Fair Use & API Availability
            </h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              Our containerized FastAPI backend deployed on Google Cloud Run utilizes enterprise rate-limiting and circuit-breaker patterns to ensure 99.9% uptime and prevent unexpected model quota starvation.
            </p>
          </div>
        </ClayCard>
      </div>

      <div className="p-6 rounded-3xl bg-[var(--surface-sunken)] border border-[var(--border)] text-xs text-text-secondary leading-relaxed">
        <h4 className="font-bold text-text-primary text-sm font-[var(--font-display)] mb-2">
          Agreement Scope
        </h4>
        <p>
          By using Crewmate, you agree to these operating terms. If you have questions regarding customized enterprise SLAs or multi-creator agency fleets, contact our open-source developer team.
        </p>
      </div>
    </div>
  )
}
